name: CI

on:
  push:
    branches:
      - main

  # Run tests for any PRs.
  pull_request:

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v33
        with:
          files: |
            **/*.rb

      - name: Run step if any file(s) in the docs folder change
        run: |
          echo "One or more files in the docs folder has changed."
          echo "List all the files that have changed: ${{ steps.changed-files.outputs.all_changed_files }}"

  # test:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Build docker
  #       run: |
  #         docker-compose build
  #     - name: Setup test database
  #       run: |
  #         docker-compose run --rm api rails db:setup RAILS_ENV=test
  #     - name: Run tests
  #       run: |
  #         docker-compose run --rm api rspec
