name: CD

on:
  pull_request:

jobs:
  deploy_to_testing:
    environment: 'test'
    needs: [test]
    test:
    runs-on: ubuntu-latest

    steps:
      - name: testing
        run: |
          echo 'deploying'
